# Build and automatically create release for plgtool on a new tag
# Based on Reloaded mod loader's build script

name: Build new Release

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}
  PUBLISH_PATH: ./Publish/Release/
  ARCHIVE_PATH: ./Publish/ToUpload/
  CHANGELOG_PATH: ./Publish/Changelog.md

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        # shell: pwsh
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Setup .NET Core SDK (8.0)
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Setup AutoChangelog
      run: npm install -g auto-changelog
      
    - name: Create Changelog
      run: |
        [System.IO.Directory]::CreateDirectory("$env:PUBLISH_PATH")
        if ($env:IS_RELEASE -eq 'true') {
            auto-changelog --sort-commits date --hide-credit --template changelog-template.hbs --commit-limit false --starting-version "$env:RELEASE_TAG" --output "$env:CHANGELOG_PATH"
        }
        else {
            auto-changelog --sort-commits date --hide-credit --template changelog-template.hbs --commit-limit false --unreleased --output "$env:CHANGELOG_PATH"
        }

    - name: Build
      run: |
        Remove-Item "Publish/Release" -Recurse -ErrorAction SilentlyContinue
        New-Item "Publish/Release" -ItemType Directory -ErrorAction SilentlyContinue
        Remove-Item "Publish/ToUpload" -Recurse -ErrorAction SilentlyContinue
        New-Item "Publish/ToUpload" -ItemType Directory -ErrorAction SilentlyContinue
        dotnet restore plgtool/plgtool.csproj
        dotnet clean plgtool/plgtool.csproj
        dotnet publish plgtool/plgtool.csproj -c Release -r win-x64 --self-contained false -o "Publish/Release"
        Compress-Archive "./Publish/Release" ${{ env.ARCHIVE_PATH }}/plgtool_${{ github.ref_name }}.zip

    - name: Upload GitHub Release Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: GitHub Release
        path: |
          ${{ env.PUBLISH_PATH }}/*

    - name: Upload to GitHub Releases (on Tag)
      uses: softprops/action-gh-release@v0.1.14
      if: env.IS_RELEASE == 'true'
      with:
        body_path: ${{ env.CHANGELOG_PATH }}
        files: ${{ env.ARCHIVE_PATH }}/*
